### ISSUE TITLE
Postcss is not working in multiple theme

### ISSUE THREAD

**Issue by sivaraj-v** [estevanmaito/tailwindcss-multi-theme#11]
postcss.config.js

```
const tailwindcss = require('tailwindcss');
const purgecss = require('@fullhuman/postcss-purgecss');

if(process.env.RUN == 'production') {
  postCssPlugins = [
    tailwindcss('./tailwind.config.js'),
    require('autoprefixer'),
    purgecss({
      content: ['./pages/**/*.js']
    }),
  ]
}
```

**Comment by estevanmaito** [comment]
Use the issue template.

**Comment by sivaraj-v** [comment]
Where is template ??

**Comment by estevanmaito** [comment]
When you open a new issue, you have the option to choose Bug or Feature. Both already have instructions inside that you should follow.

Open a new issue (probably a **Bug report**) or edit this one to add more information about your problem.
