### ISSUE TITLE
ask for SSR supporting

### ISSUE THREAD

**Issue by kuleyu** [estevanmaito/tailwindcss-multi-theme#12]
**Is your feature request related to a problem? Please describe.**
it seems that this plugin is not support SSR currently. When using  in sever side rending, it will cause error: "window is not defined".

As for this, i can't use it in a Gridsome/Gastby project. But really love this plugin as it is more easily to configure multi-theme than others.

Hope it will be supported someday!

**Comment by estevanmaito** [comment]
Could you PLEASE, use the issue template and provide what is asked there (like what's your code, the full error message, a reproducible example would be great, etc.)?

This same plugin is used in [Windmill React UI](https://github.com/estevanmaito/windmill-react-ui) (in the library and its documentation) and is SSR'ed with Next.

The plugin itself doesn't even contain the word `window`, but it could throw this error if you're using `prefers-dark.js` https://github.com/estevanmaito/tailwindcss-multi-theme/blob/master/prefers-dark.js
