### ISSUE TITLE
How to use with @apply

### ISSUE THREAD

**Issue by limatheus** [estevanmaito/tailwindcss-multi-theme#13]
### Problem description:

Hi @estevanmaito first of all, thank you for this awesome plugin!

My question is how can I use the dark: especification with ` @aplly`?

I`m not able to use with the following sintaxe

```(scss)
.toggle{
    @apply border-4 border-gray-300 dark:border-dark-gray-300;
}
```

I try scape using slashes, quotes etc, but not works...

Can you help me with this?

**Comment by estevanmaito** [comment]
This is the preferred way, as stated in the docs: https://github.com/estevanmaito/tailwindcss-multi-theme#using-inside-css-with-apply

I didn't test yet, but Tailwind now supports complex style classes inside `@apply` using experimental flags (^1.7.0): https://github.com/tailwindlabs/tailwindcss/releases/tag/v1.7.0#use-apply-with-variants-and-other-complex-classes

With the later approach (needs to be confirmed), you could write the same way as your example code.

**Comment by limatheus** [comment]
@estevanmaito thank`s brother!
The complex classes on ^1.7.0 works like a charm with `@apply`
 
The code below is working now :raised_hands:  :raised_hands:  :raised_hands: 
```(css)
.toggle-checkbox{
    @apply border-4 border-gray-300 dark:border-dark-gray-600;
}
```

**Comment by estevanmaito** [comment]
Great!!

I'll update the docs. Thank you.
