### ISSUE TITLE
Versioning dependency issue

### ISSUE THREAD

**Issue by RJFares** [estevanmaito/tailwindcss-multi-theme#17]
I keep getting the below error when compiling with npm:

npm ERR! peer dep missing: tailwindcss@1.4.6, required by tailwindcss-multi-theme@1.0.3

My current version is tailwindcss@1.9.4

**Comment by estevanmaito** [comment]
Thanks for the report. It surprises me that it wasn't raised before.

I'll fix that 👍

**Comment by RJFares** [comment]
Because even I have been ignoring it for a couple of months (the warning can be ignored and compilation will run)
but the fix is easy so since I was on github... :)

**Comment by AnasSharif** [comment]
@estevanmaito facing issue like above but if when i install after tailwind installation, If install before tailwind installation its show just warning.

```
npm ERR! While resolving: undefined@undefined
npm ERR! Found: tailwindcss@3.0.13
npm ERR! node_modules/tailwindcss
npm ERR!   dev tailwindcss@"^3.0.13" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@"^1.4.6" from tailwindcss-multi-theme@1.0.4
npm ERR! node_modules/tailwindcss-multi-theme
npm ERR!   tailwindcss-multi-theme@"*" from the root project
```

**Comment by tiznull** [comment]
I believe this package is abandoned and should be marked as such. No updates for two years, tailwind dependencies are very outdated. Projects that are using this package cannot update anymore. It would be great if the person that developed this package offered an alternative.
