### ISSUE TITLE
Focus and Hover dont work

### ISSUE THREAD

**Issue by scalarerp** [estevanmaito/tailwindcss-multi-theme#3]
version: "tailwindcss-multi-theme": "^1.0.3"
in my code this work:
focus:outline-none hover:text-gray-600 hover:bg-gray-300

But when i install Multi-Theme then stop work.
With Multi-theme:

![2020-06-17_14-21-53](https://user-images.githubusercontent.com/17085986/84929570-6132cb80-b0a6-11ea-899f-09032e8b10b7.gif)

Without:

![2020-06-17_14-24-15](https://user-images.githubusercontent.com/17085986/84929568-60019e80-b0a6-11ea-8052-3ee4b127a17b.gif)

**Comment by estevanmaito** [comment]
It's how variants work in Tailwind.

The default for `backgroundColor` is `backgroundColor: ['responsive', 'hover', 'focus'],`

If you just add `dark`, you're overwriting the default, in other words, you're erasing responsive, hover and focus. Here is a guide for Tailwind defaults: https://tailwindcss.com/docs/pseudo-class-variants/#default-variants-reference

The usage guide also shows exactly the solution for your problem: https://github.com/estevanmaito/tailwindcss-multi-theme#-usage
