### ISSUE TITLE
CSS functions?

### ISSUE THREAD

**Issue by tgdn** [estevanmaito/tailwindcss-multi-theme#4]
First, this is a great plugin, and a great project, thanks.

**Is your feature request related to a problem? Please describe.**
It's great to have everything in the html:  `<div class="dark:bg-blue-100"></div>`.

**Describe the solution you'd like**
But what would be even better would be to have something that can be used in CSS like the `@screen` directive:

```css
input {
	@apply bg-gray-300;
}

input:focus {
	@apply bg-white;
}

@theme dark {
	input {
		@apply bg-gray-800;
	}
	input:focus {
		@apply bg-gray-500;
	}
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by estevanmaito** [comment]
You could use something like

```css
.theme-dark {
  input {
    @apply text-blue-300;
  }
}
```

and just place every style that you need inside the `.theme-dark` rule. If you think this is helpful, I could put it in the docs.

**Comment by laymonage** [comment]
I think it's a good idea to mention that it needs [nesting support](https://tailwindcss.com/docs/using-with-preprocessors/#nesting).

If users don't want to use nesting, they can do something like:

```css
.theme-dark a {
  @apply text-blue-300;
}
```

**Comment by tgdn** [comment]
This does the trick. I suppose I only looked at it briefly and didn’t think of the obvious. 
Thanks for you help!
Thomas

**Comment by estevanmaito** [comment]
> 
> 
> I think it's a good idea to mention that it needs [nesting support](https://tailwindcss.com/docs/using-with-preprocessors/#nesting).
> 
> If users don't want to use nesting, they can do something like:
> 
> ```css
> .theme-dark a {
>   @apply text-blue-300;
> }
> ```

Added to the docs. Thanks!

**Comment by tgdn** [comment]
I agree. Awesome thanks. Great work!
